version: "3.5"
services:
  app:
    build:
      context: ./
    container_name: langding-page
    restart: always
    image: registry.gitlab.com/rogo2/project/rogo:1.0.6
    ports:
      - 3006:8080
